DROP TABLE IF EXISTS `tabelnegara`;

CREATE TABLE `tabelnegara` (
	`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
	`negara` varchar(100) NOT NULL DEFAULT '',
	`alpha2` varchar(3) NOT NULL DEFAULT '',
	`alpha3` varchar(4) NOT NULL DEFAULT '',
	`numerik` varchar(5) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	KEY `kodenegara` (`alpha2`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


--
-- Dumping data for table `apps_countries`
--

INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Afganistan', 'AF', 'AFG', '4');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Afrika Selatan', 'ZA', 'ZAF', '710');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Afrika Tengah. Republik', 'CF', 'CAF', '140');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Aland. Kepulauan', 'AX', 'ALA', '248');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Albania', 'AL', 'ALB', '8');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Aljazair', 'DZ', 'DZA', '12');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Amerika Serikat', 'US', 'USA', '840');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Andorra', 'AD', 'AND', '20');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Angola', 'AO', 'AGO', '24');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Anguilla', 'AI', 'AIA', '660');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Antarktika', 'AQ', 'ATA', '10');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Antigua dan Barbuda', 'AG', 'ATG', '28');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Antillen Belanda', 'AN', 'ANT', '530');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Arab Saudi', 'SA', 'SAU', '682');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Argentina', 'AR', 'ARG', '32');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Armenia', 'AM', 'ARM', '51');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Aruba', 'AW', 'ABW', '533');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Australia', 'AU', 'AUS', '36');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Austria', 'AT', 'AUT', '40');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Azerbaijan', 'AZ', 'AZE', '31');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bahama', 'BS', 'BHS', '44');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bahrain', 'BH', 'BHR', '48');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bangladesh', 'BD', 'BGD', '50');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Barbados', 'BB', 'BRB', '52');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Belanda', 'NL', 'NLD', '528');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Belarus', 'BY', 'BLR', '112');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Belgia', 'BE', 'BEL', '56');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Belize', 'BZ', 'BLZ', '84');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Benin', 'BJ', 'BEN', '204');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bermuda', 'BM', 'BMU', '60');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bhutan', 'BT', 'BTN', '64');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bolivia', 'BO', 'BOL', '68');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bosnia dan Herzegovina', 'BA', 'BIH', '70');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Botswana', 'BW', 'BWA', '72');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bouvet. Pulau', 'BV', 'BVT', '74');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Brasil', 'BR', 'BRA', '76');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Britania Raya', 'GB', 'GBR', '826');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Brunei', 'BN', 'BRN', '96');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Bulgaria', 'BG', 'BGR', '100');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Burkina Faso', 'BF', 'BFA', '854');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Burundi', 'BI', 'BDI', '108');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Cayman. Kepulauan', 'KY', 'CYM', '136');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Chad', 'TD', 'TCD', '148');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Ceko. Republik', 'CZ', 'CZE', '203');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Chili', 'CL', 'CHL', '152');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Cocos (Keeling). Kepulauan', 'CC', 'CCK', '166');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Cook. Kepulauan', 'CK', 'COK', '184');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Denmark', 'DK', 'DNK', '208');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Djibouti', 'DJ', 'DJI', '262');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Dominika', 'DM', 'DMA', '212');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Dominika. Republik', 'DO', 'DOM', '214');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Ekuador', 'EC', 'ECU', '218');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'El Salvador', 'SV', 'SLV', '222');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Eritrea', 'ER', 'ERI', '232');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Estonia', 'EE', 'EST', '233');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Ethiopia', 'ET', 'ETH', '231');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Falkland. Kepulauan', 'FK', 'FLK', '238');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Faroe. Kepulauan', 'FO', 'FRO', '234');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Fiji', 'FJ', 'FJI', '242');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Filipina', 'PH', 'PHL', '608');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Finlandia', 'FI', 'FIN', '246');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Gabon', 'GA', 'GAB', '266');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Gambia', 'GM', 'GMB', '270');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Georgia', 'GE', 'GEO', '268');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Georgia Selatan dan Kepulauan Sandwich Selatan', 'GS', 'SGS', '239');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Ghana', 'GH', 'GHA', '288');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Gibraltar', 'GI', 'GIB', '292');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Greenland', 'GL', 'GRL', '304');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Grenada', 'GD', 'GRD', '308');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guadeloupe', 'GP', 'GLP', '312');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guam', 'GU', 'GUM', '316');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guatemala', 'GT', 'GTM', '320');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guernsey', 'GG', 'GGY', '831');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guinea', 'GN', 'GIN', '324');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guinea-Bissau', 'GW', 'GNB', '624');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guinea Khatulistiwa', 'GQ', 'GNQ', '226');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guyana', 'GY', 'GUY', '328');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Guyana Perancis', 'GF', 'GUF', '254');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Haiti', 'HT', 'HTI', '332');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Heard dan Kepulauan McDonald. Pulau', 'HM', 'HMD', '334');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Honduras', 'HN', 'HND', '340');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Hong Kong', 'HK', 'HKG', '344');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Hongaria', 'HU', 'HUN', '348');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Islandia', 'IS', 'ISL', '352');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'India', 'IN', 'IND', '356');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Indonesia', 'ID', 'IDN', '360');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Irak', 'IQ', 'IRQ', '368');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Iran', 'IR', 'IRN', '364');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Irlandia. Republik', 'IE', 'IRL', '372');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Israel', 'IL', 'ISR', '376');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Italia', 'IT', 'ITA', '380');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Jamaika', 'JM', 'JAM', '388');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Jepang', 'JP', 'JPN', '392');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Jerman', 'DE', 'DEU', '276');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Jersey', 'JE', 'JEY', '832');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kaledonia Baru', 'NC', 'NCL', '540');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kamboja', 'KH', 'KHM', '116');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kamerun', 'CM', 'CMR', '120');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kanada', 'CA', 'CAN', '124');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kazakhstan', 'KZ', 'KAZ', '398');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kenya', 'KE', 'KEN', '404');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kiribati', 'KI', 'KIR', '296');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kirgizstan', 'KG', 'KGZ', '417');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kolombia', 'CO', 'COL', '170');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Komoro', 'KM', 'COM', '174');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kongo. Republik', 'CG', 'COG', '178');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kongo. Republik Demokratik', 'CD', 'COD', '180');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Korea. Republik', 'KR', 'KOR', '410');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Korea. Republik Rakyat Demokratik', 'KP', 'PRK', '408');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kosta Rika', 'CR', 'CRI', '188');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kroasia', 'HR', 'HRV', '191');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kuba', 'CU', 'CUB', '192');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kuwait', 'KW', 'KWT', '414');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Laos', 'LA', 'LAO', '418');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Latvia', 'LV', 'LVA', '428');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Lebanon', 'LB', 'LBN', '422');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Lesotho', 'LS', 'LSO', '426');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Liberia', 'LR', 'LBR', '430');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Libya', 'LY', 'LBY', '434');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Liechtenstein', 'LI', 'LIE', '438');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Lituania', 'LT', 'LTU', '440');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Luksemburg', 'LU', 'LUX', '442');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Makau', 'MO', 'MAC', '446');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Makedonia. Republik', 'MK', 'MKD', '807');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Madagaskar', 'MG', 'MDG', '450');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Malawi', 'MW', 'MWI', '454');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Malaysia', 'MY', 'MYS', '458');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Maladewa', 'MV', 'MDV', '462');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mali', 'ML', 'MLI', '466');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Malta', 'MT', 'MLT', '470');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Man. Pulau', 'IM', 'IMN', '833');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mariana Utara. Kepulauan', 'MP', 'MNP', '580');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Maroko', 'MA', 'MAR', '504');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Marshall. Kepulauan', 'MH', 'MHL', '584');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Martinik', 'MQ', 'MTQ', '474');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mauritania', 'MR', 'MRT', '478');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mauritius', 'MU', 'MUS', '480');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mayotte', 'YT', 'MYT', '175');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Meksiko', 'MX', 'MEX', '484');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mikronesia. Federasi', 'FM', 'FSM', '583');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Moldova', 'MD', 'MDA', '498');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mesir', 'EG', 'EGY', '818');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Monako', 'MC', 'MCO', '492');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Kepulauan Terluar Kecil Amerika Serikat', 'UM', 'UMI', '581');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mongolia', 'MN', 'MNG', '496');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Montenegro', 'ME', 'MNE', '499');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Montserrat', 'MS', 'MSR', '500');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Mozambik', 'MZ', 'MOZ', '508');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Myanmar', 'MM', 'MMR', '104');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Namibia', 'NA', 'NAM', '516');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Nauru', 'NR', 'NRU', '520');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Natal. Pulau', 'CX', 'CXR', '162');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Nepal', 'NP', 'NPL', '524');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Nikaragua', 'NI', 'NIC', '558');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Niger', 'NE', 'NER', '562');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Nigeria', 'NG', 'NGA', '566');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Niue', 'NU', 'NIU', '570');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Norfolk. Pulau', 'NF', 'NFK', '574');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Norwegia', 'NO', 'NOR', '578');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Oman', 'OM', 'OMN', '512');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Pakistan', 'PK', 'PAK', '586');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Palau', 'PW', 'PLW', '585');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Palestina', 'PS', 'PSE', '275');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Panama', 'PA', 'PAN', '591');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Pantai Gading', 'CI', 'CIV', '384');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Papua Nugini', 'PG', 'PNG', '598');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Paraguay', 'PY', 'PRY', '600');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Perancis', 'FR', 'FRA', '250');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Perancis Selatan. Teritori', 'TF', 'ATF', '260');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Peru', 'PE', 'PER', '604');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Pitcairn. Kepulauan', 'PN', 'PCN', '612');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Polandia', 'PL', 'POL', '616');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Polinesia Perancis', 'PF', 'PYF', '258');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Portugal', 'PT', 'PRT', '620');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Puerto Riko', 'PR', 'PRI', '630');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Qatar', 'QA', 'QAT', '634');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'R‚union', 'RE', 'REU', '638');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Rumania', 'RO', 'ROU', '642');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Rusia', 'RU', 'RUS', '643');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Rwanda', 'RW', 'RWA', '646');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Sahara Barat', 'EH', 'ESH', '732');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint-Barth‚lemy', 'BL', 'BLM', '652');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint Helena. Ascension. dan Tristan da Cunha', 'SH', 'SHN', '654');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint Kitts dan Nevis', 'KN', 'KNA', '659');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint Lucia', 'LC', 'LCA', '662');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint Martin (Perancis)', 'MF', 'MAF', '663');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint Pierre dan Miquelon', 'PM', 'SPM', '666');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Saint Vincent dan Grenadines', 'VC', 'VCT', '670');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Samoa', 'WS', 'WSM', '882');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Samoa Amerika', 'AS', 'ASM', '16');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Samudra Hindia Britania. Teritori', 'IO', 'IOT', '86');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'San Marino', 'SM', 'SMR', '674');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Sao Tome dan Principe', 'ST', 'STP', '678');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Selandia Baru', 'NZ', 'NZL', '554');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Senegal', 'SN', 'SEN', '686');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Serbia', 'RS', 'SRB', '688');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Seychelles', 'SC', 'SYC', '690');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Sierra Leone', 'SL', 'SLE', '694');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Singapura', 'SG', 'SGP', '702');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Siprus', 'CY', 'CYP', '196');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Slovenia', 'SI', 'SVN', '705');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Slowakia', 'SK', 'SVK', '703');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Solomon. Kepulauan', 'SB', 'SLB', '90');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Somalia', 'SO', 'SOM', '706');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Spanyol', 'ES', 'ESP', '724');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Sri Lanka', 'LK', 'LKA', '144');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Sudan', 'SD', 'SDN', '736');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Suriah', 'SY', 'SYR', '760');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Suriname', 'SR', 'SUR', '740');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Svalbard dan Jan Mayen', 'SJ', 'SJM', '744');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Swaziland', 'SZ', 'SWZ', '748');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Swedia', 'SE', 'SWE', '752');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Swiss', 'CH', 'CHE', '756');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Taiwan', 'TW', 'TWN', '158');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tajikistan', 'TJ', 'TJK', '762');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tanjung Verde', 'CV', 'CPV', '132');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tanzania', 'TZ', 'TZA', '834');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Thailand', 'TH', 'THA', '764');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Timor Leste', 'TL', 'TLS', '626');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tiongkok. Republik Rakyat', 'CN', 'CHN', '156');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Togo', 'TG', 'TGO', '768');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tokelau', 'TK', 'TKL', '772');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tonga', 'TO', 'TON', '776');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Trinidad dan Tobago', 'TT', 'TTO', '780');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tunisia', 'TN', 'TUN', '788');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Turki', 'TR', 'TUR', '792');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Turkmenistan', 'TM', 'TKM', '795');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Turks dan Caicos. Kepulauan', 'TC', 'TCA', '796');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Tuvalu', 'TV', 'TUV', '798');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Uganda', 'UG', 'UGA', '800');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Ukraina', 'UA', 'UKR', '804');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Uni Emirat Arab', 'AE', 'ARE', '784');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Uruguay', 'UY', 'URY', '858');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Uzbekistan', 'UZ', 'UZB', '860');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Vanuatu', 'VU', 'VUT', '548');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Vatikan', 'VA', 'VAT', '336');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Venezuela', 'VE', 'VEN', '862');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Vietnam', 'VN', 'VNM', '704');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Virgin Amerika Serikat. Kepulauan', 'VI', 'VIR', '850');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Virgin Britania Raya. Kepulauan', 'VG', 'VGB', '92');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Wallis dan Futuna', 'WF', 'WLF', '876');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Yaman', 'YE', 'YEM', '887');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Yordania', 'JO', 'JOR', '400');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Yunani', 'GR', 'GRC', '300');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Zambia', 'ZM', 'ZMB', '894');
INSERT INTO `tabelnegara` (`id`, `negara`, `alpha2`, `alpha3`, `numerik`) VALUES (null, 'Zimbabwe', 'ZW', 'ZWE', '716');
